
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.UIManager;
import javax.swing.text.DefaultEditorKit;
/**
 *
 * @author Tautvydas Bagocius
 */
public class principal extends javax.swing.JFrame {
    //instanciamos los atributos que vamos a necesitar para el control de los cambios y el cambio del título
    private static int contador =0;
    String titulo="nuevo";
    //métodos getter y setter del contador
    public static void setContador(int n){
        principal.contador=n;
    }
    public static int getContador(){
        return contador;
    }
    
    /**
     * Creates new form principal
     */
    public principal() {
        //iniciamos los componenetes
        initComponents();
        //posicionamos el JFrame en medio
        this.setLocationRelativeTo(null);
        //Le asignamos un icono para que no sea el por defecto de Java
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/notepad-ico.png"));
        this.setIconImage(icon);
        //Le agregamos un título inicial, que cuando se habra un fichero diferente se ira cambiando
        this.setTitle(titulo);
        //le agregamos un listener al jtextarea para detectar los cambios que se realizan
        jTextArea1.getDocument().addDocumentListener(new controlaCambiosTexto());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        abrir = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        copiar = new javax.swing.JButton(new DefaultEditorKit.CopyAction());
        cortar = new javax.swing.JButton(new DefaultEditorKit.CutAction());
        pegar = new javax.swing.JButton(new DefaultEditorKit.PasteAction());
        jMenuBar1 = new javax.swing.JMenuBar();
        itemAbrir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        itemCopiar = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem(new DefaultEditorKit.CopyAction());
        itemCortar = new javax.swing.JMenuItem(new DefaultEditorKit.CutAction());
        itemPegar = new javax.swing.JMenuItem(new DefaultEditorKit.PasteAction());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abrir_fichero.png"))); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jPanel1.add(abrir);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar_fichero.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar);

        copiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copy-icon.png"))); // NOI18N
        copiar.setText("Copiar");
        jPanel1.add(copiar);

        cortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Action-cut-icon.png"))); // NOI18N
        cortar.setText("Cortar");
        jPanel1.add(cortar);

        pegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paste-ico.png"))); // NOI18N
        pegar.setText("Pegar");
        jPanel1.add(pegar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        itemAbrir.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/abrir_fichero.png"))); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemAbrir.add(jMenuItem1);

        itemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar_fichero.png"))); // NOI18N
        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        itemAbrir.add(itemGuardar);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        itemAbrir.add(itemSalir);

        jMenuBar1.add(itemAbrir);

        itemCopiar.setText("Editor");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copy-icon.png"))); // NOI18N
        jMenuItem4.setText("Copiar");
        itemCopiar.add(jMenuItem4);

        itemCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Action-cut-icon.png"))); // NOI18N
        itemCortar.setText("Cortar");
        itemCopiar.add(itemCortar);

        itemPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paste-ico.png"))); // NOI18N
        itemPegar.setText("Pegar");
        itemCopiar.add(itemPegar);

        jMenuBar1.add(itemCopiar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controlaCambiosTexto controlador = new controlaCambiosTexto();
        controlador.controladorAbrir(contador, jTextArea1);
        abrir abrir = new abrir(new File("."),jTextArea1);
        this.setTitle(abrir.getTitulo());
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
       guardar guardar = new guardar(new File("."),jTextArea1);
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        controlaCambiosTexto controlador = new controlaCambiosTexto();
        controlador.controlador(contador, jTextArea1);
        
    }//GEN-LAST:event_itemSalirActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        controlaCambiosTexto controlador = new controlaCambiosTexto();
        controlador.controladorAbrir(contador, jTextArea1);
        abrir abrir = new abrir(new File("."),jTextArea1);
        this.setTitle(abrir.getTitulo());
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar guardar = new guardar(new File("."),jTextArea1);
    }//GEN-LAST:event_guardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlaCambiosTexto controlador = new controlaCambiosTexto();
        controlador.controlador(contador, jTextArea1);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
             
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton copiar;
    private javax.swing.JButton cortar;
    private javax.swing.JButton guardar;
    private javax.swing.JMenu itemAbrir;
    private javax.swing.JMenu itemCopiar;
    private javax.swing.JMenuItem itemCortar;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemPegar;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pegar;
    // End of variables declaration//GEN-END:variables

    
    
}
